name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - .reuse
      - LICENSES/
      - LICENSE
      - .gitignore
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - .reuse
      - LICENSES/
      - LICENSE
      - .gitignore
      - "**.md"

jobs:
  lint:
    name: run-linter
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.10.1
