name: rt-bootstrapper release

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  tests:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  build-image:
    needs: tests
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build_image.yml

  generate-release:
    needs: build-image
    if: needs.build-image.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and uploading assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Generate Release module artifacts for tag release
        run: |
          set -e
          make build-installer 
          cp ./dist/install.yaml rt-bootstrapper.yaml
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/rt-bootstrapper:${{ github.ref_name }}

      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./rt-bootstrapper.yaml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release-report:
    needs: generate-release
    if: needs.generate-release.result == 'success'
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/upload-release-report.yaml
    with:
      release_version: ${{ github.ref_name }}
    secrets:
      RELEASE_LOG_UPLOADER_SA: ${{ secrets.RELEASE_LOG_UPLOADER_SA }}
